spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATA_SOURCE_URL}
    username: ${SPRING_DATA_SOURCE_USERNAME}
    password: ${SPRING_DATA_SOURCE_PASSWORD}

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

server:
  port: ${PORT:8080}